import {useMemo,useState} from "react";
import {Activity,BarChart3,Building2,Search,Users} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import StatCard from "../components/common/StatCard";
import {activities,cities} from "../data/mockData";

const users=["Olivia Martin","Noah Williams","Emma Patel","Liam Johnson","Ava Thompson","Ethan Wilson"];
const tabs=[["users","Manage Users",Users],["cities","Popular cities",Building2],["activities","Popular Activities",Activity],["analytics","User Trends and Analytics",BarChart3]];
export default function AdminDashboard(){
 const[tab,setTab]=useState("users");const[q,setQ]=useState("");const filteredUsers=users.filter(user=>user.toLowerCase().includes(q.toLowerCase()));
 return <section className="page admin-page"><PageHeader title="Admin panel" subtitle="Manage the Ekado experience and understand how people use it."/><div className="admin-toolbar"><label><Search size={16}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search users, cities, or activities"/></label><select aria-label="Group admin results"><option>Group by</option><option>Category</option><option>Popularity</option></select><button className="btn btn-outline">Filter</button><select aria-label="Sort admin results"><option>Sort by...</option><option>Most popular</option><option>Newest</option></select></div><div className="admin-tabs">{tabs.map(([id,label,Icon])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon size={15}/><span>{label}</span></button>)}</div>{tab==="users"&&<UserPanel users={filteredUsers}/>} {tab==="cities"&&<RankPanel title="Popular cities" description="See which destinations users are choosing most often." items={cities.map(city=>({name:city.name,detail:`${city.country} · ${city.region}`,value:`${city.popularity}%`,emoji:city.emoji}))}/>} {tab==="activities"&&<RankPanel title="Popular activities" description="See the experiences being added to itineraries across the platform." items={activities.map(activity=>({name:activity.name,detail:`${activity.city} · ${activity.type}`,value:activity.cost===0?"Free":`$${activity.cost}`,emoji:activity.emoji}))}/>} {tab==="analytics"&&<AnalyticsPanel/>}</section>
}
function UserPanel({users:items}){return <div className="admin-content"><div className="admin-section-copy"><span className="eyebrow">Platform operations</span><h2>Manage users</h2><p>Review account activity and keep the community healthy.</p></div><div className="admin-stats"><StatCard icon="👥" label="Total Users" value="2,481" hint="+12.5% this month"/><StatCard icon="🧳" label="Trips Created" value="8,642" hint="+18% this month"/></div><div className="admin-table">{items.map((user,index)=><div className="admin-user" key={user}><div className="admin-avatar">{user.split(" ").map(part=>part[0]).join("")}</div><div><b>{user}</b><small>{user.toLowerCase().replace(" ",".")}@example.com</small></div><span>{index+1} trips</span><em>Active</em><button>Manage</button></div>)}</div></div>}
function RankPanel({title,description,items}){return <div className="admin-content"><div className="admin-section-copy"><span className="eyebrow">Admin insights</span><h2>{title}</h2><p>{description}</p></div><div className="admin-ranking">{items.map((item,index)=><div className="admin-rank" key={item.name}><strong>0{index+1}</strong><span className="rank-visual">{item.emoji}</span><div><b>{item.name}</b><small>{item.detail}</small></div><span className="rank-value">{item.value}</span></div>)}</div></div>}
function AnalyticsPanel(){return <div className="admin-content"><div className="admin-section-copy"><span className="eyebrow">Platform intelligence</span><h2>User trends and analytics</h2><p>Track adoption, trip creation, and engagement as the community grows.</p></div><div className="analytics-layout"><div className="analytics-chart">{[34,48,43,62,58,74,69,91,82,105,98,122].map((height,index)=><div key={index} style={{height}}><span>{index+1}</span></div>)}</div><div className="analytics-highlights"><div><strong>72%</strong><span>Engagement rate</span></div><div><strong>+18%</strong><span>Trips this month</span></div><div><strong>4.8</strong><span>Average rating</span></div></div></div></div>}