import {useMemo,useState} from "react";
import {ArrowDownAZ,Check,Filter,Plus,Search,SlidersHorizontal} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import {cities} from "../data/mockData";

export default function CitySearch(){
 const[q,setQ]=useState("");const[region,setRegion]=useState("All regions");const[sort,setSort]=useState("Popular");const[added,setAdded]=useState([]);
 const list=useMemo(()=>cities.filter(city=>(region==="All regions"||city.region===region)&&`${city.name} ${city.country} ${city.region}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="Popular"?b.popularity-a.popularity:a.name.localeCompare(b.name)),[q,region,sort]);
 const toggle=city=>setAdded(current=>current.includes(city)?current.filter(item=>item!==city):[...current,city]);
 return <section className="page search-results-page"><PageHeader title="Explore cities" subtitle="Find the right place for your next route and add it to your trip."/><div className="search-page-toolbar"><label className="result-search"><Search size={17}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search by city, country, or region"/></label><select value={region} onChange={event=>setRegion(event.target.value)} aria-label="Group by region"><option>All regions</option><option>Europe</option><option>Asia</option><option>Middle East</option></select><button className="btn btn-outline"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort city results"><option>Popular</option><option>Name</option></select><SlidersHorizontal className="search-sliders" size={17}/></div><div className="result-heading"><div><span className="eyebrow">Destination directory</span><h2>Results</h2></div><span>{list.length} places</span></div><div className="result-list">{list.map(city=><article className="result-row" key={city.name}><div className="result-art">{city.emoji}</div><div className="result-copy"><h3>{city.name}, {city.country}</h3><p>{city.region} · {city.cost} cost index · {city.popularity}% popularity</p><small>Popular with Ekado travelers for its memorable local experiences.</small></div><button className={`btn small ${added.includes(city.name)?"btn-success":"btn-primary"}`} onClick={()=>toggle(city.name)}>{added.includes(city.name)?<><Check size={15}/> Added</>:<><Plus size={15}/> Add to Trip</>}</button></article>)}{!list.length&&<div className="search-empty">No cities match your search. Try a country or region.</div>}</div></section>
}