import {useMemo,useState} from "react";
import {CalendarDays,ChevronDown,Filter,List,Search,Share2,Pencil} from "lucide-react";
import {Link} from "react-router-dom";
import PageHeader from "../components/common/PageHeader";
import {itinerary} from "../data/mockData";

export default function ItineraryView(){
 const[q,setQ]=useState("");const[sort,setSort]=useState("Day");
 const days=useMemo(()=>itinerary.filter(item=>`${item.city} ${item.activities.join(" ")}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="Expense"?b.cost-a.cost:a.day.localeCompare(b.day)),[q,sort]);
 return <section className="page itinerary-view-page"><PageHeader title="European Escape" subtitle="12 Sep – 22 Sep 2026 · Paris → Rome → Barcelona" action={<div className="action-group"><Link className="btn btn-outline" to="/shared/1"><Share2 size={17}/> Share</Link><Link className="btn btn-primary" to="/trips/1/builder"><Pencil size={17}/> Edit</Link></div>}/><div className="itinerary-toolbar"><label><Search size={16}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search itinerary"/></label><select aria-label="Group itinerary"><option>Group by day</option><option>Group by city</option></select><button className="btn btn-outline"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort itinerary"><option>Day</option><option>Expense</option></select><button className="icon-btn" title="More itinerary options"><ChevronDown size={16}/></button></div><div className="itinerary-title"><div><span className="eyebrow">Your trip at a glance</span><h2>Itinerary for a selected place</h2></div><Link className="view-calendar" to="/calendar"><CalendarDays size={15}/> Calendar</Link></div><div className="itinerary-column-head"><span>Day</span><b>Physical activity</b><b>Expense</b></div><div className="day-list">{days.map(item=><article className="itinerary-day" key={item.day}><div className="day-chip">{item.day}</div><div className="day-activities"><span className="city-label">📍 {item.city}</span>{item.activities.map((activity,index)=><div className="itinerary-activity" key={activity}><span className="activity-dot">{index+1}</span><div><b>{activity}</b><small>{index===0?"Morning plan":"Afternoon plan"} · {item.city}</small></div></div>)}</div><div className="day-expense"><strong>${item.cost}</strong><small>planned</small></div></article>)}{!days.length&&<div className="itinerary-empty">No itinerary items match your search.</div>}</div></section>
}