import {useMemo,useState} from "react";
import {Check,Filter,Plus,Search,SlidersHorizontal} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import {activities} from "../data/mockData";

export default function ActivitySearch(){
 const[q,setQ]=useState("");const[type,setType]=useState("All types");const[sort,setSort]=useState("Recommended");const[added,setAdded]=useState([]);
 const list=useMemo(()=>activities.filter(activity=>(type==="All types"||activity.type===type)&&`${activity.name} ${activity.city} ${activity.type}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="Price"?a.cost-b.cost:a.name.localeCompare(b.name)),[q,type,sort]);
 const toggle=id=>setAdded(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 return <section className="page search-results-page"><PageHeader title="Find activities" subtitle="Choose experiences that make every stop memorable."/><div className="search-page-toolbar"><label className="result-search"><Search size={17}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search activities, cities, or experiences"/></label><select value={type} onChange={event=>setType(event.target.value)} aria-label="Group by activity type"><option>All types</option><option>Sightseeing</option><option>Food</option><option>Adventure</option><option>Relaxation</option></select><button className="btn btn-outline"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort activity results"><option>Recommended</option><option>Price</option></select><SlidersHorizontal className="search-sliders" size={17}/></div><div className="result-heading"><div><span className="eyebrow">Build your days</span><h2>Results</h2></div><span>{list.length} experiences</span></div><div className="result-list">{list.map(activity=><article className="result-row activity-result" key={activity.id}><div className="result-art activity-result-art">{activity.emoji}</div><div className="result-copy"><div className="result-tag">{activity.type}</div><h3>{activity.name}</h3><p>{activity.city} · {activity.duration} · {activity.cost===0?"Free":"$"+activity.cost}</p><small>A considered addition to your itinerary, ready to be placed on the right day.</small></div><button className={`btn small ${added.includes(activity.id)?"btn-success":"btn-primary"}`} onClick={()=>toggle(activity.id)}>{added.includes(activity.id)?<><Check size={15}/> Added</>:<><Plus size={15}/> Add</>}</button></article>)}{!list.length&&<div className="search-empty">No activities match your search. Try a city or activity type.</div>}</div></section>
}