import {useMemo,useState} from "react";
import {ChevronLeft,ChevronRight,Filter,Search} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import {itinerary} from "../data/mockData";

const monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"];
const events=[...itinerary,{day:"Day 4",date:"18 Sep",city:"Barcelona",activities:["Gothic Quarter Walk"],cost:95}];
export default function CalendarTimeline(){
 const[today,setToday]=useState(new Date(2026,8,1));const[q,setQ]=useState("");const[showTrips,setShowTrips]=useState(true);
 const year=today.getFullYear(),month=today.getMonth(),daysInMonth=new Date(year,month+1,0).getDate(),startDay=(new Date(year,month,1).getDay()+6)%7;
 const previous=()=>setToday(new Date(year,month-1,1));const next=()=>setToday(new Date(year,month+1,1));const jumpToday=()=>setToday(new Date());
 const visible=useMemo(()=>events.filter(event=>showTrips&&`${event.city} ${event.activities.join(" ")}`.toLowerCase().includes(q.toLowerCase())),[q,showTrips]);
 return <section className="page calendar-page"><PageHeader title="Calendar" subtitle="See every trip, activity, and important date in one clear view."/><div className="calendar-toolbar"><label><Search size={16}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search calendar"/></label><select aria-label="Group calendar"><option>Group by trip</option><option>Group by city</option></select><button className={`btn ${showTrips?"btn-primary":"btn-outline"}`} onClick={()=>setShowTrips(!showTrips)}><Filter size={15}/> {showTrips?"Trips on":"Trips off"}</button><button className="btn btn-outline" onClick={jumpToday}>Today</button></div><div className="calendar-card section-card"><div className="calendar-title"><div><span className="eyebrow">Your travel schedule</span><h2>Calendar view</h2></div><div className="month-nav"><button className="icon-btn" onClick={previous} title="Previous month"><ChevronLeft size={17}/></button><strong>{monthNames[month]} {year}</strong><button className="icon-btn" onClick={next} title="Next month"><ChevronRight size={17}/></button></div></div><div className="weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><b key={day}>{day}</b>)}</div><div className="calendar-grid">{Array.from({length:startDay+daysInMonth},(_,index)=>{if(index<startDay)return <div className="calendar-day blank" key={`blank-${index}`}/>;const day=index-startDay+1;const matches=visible.filter(event=>parseInt(event.date)===day);return <div className={`calendar-day ${matches.length?"has-event":""}`} key={day}><span>{day}</span>{matches.map(event=><div className="calendar-event" key={event.city}><b>{event.city}</b><small>{event.activities[0]}</small></div>)}</div>})}</div></div></section>
}