import {useMemo,useState} from "react";
import {Filter,Heart,MessageCircle,Plus,Search,Share2,SlidersHorizontal} from "lucide-react";
import PageHeader from "../components/common/PageHeader";

const initialPosts=[
 {id:1,user:"Maya Chen",initials:"MC",title:"A slower way through Kyoto",text:"Three quiet mornings, one tiny coffee shop, and the best walk along the Philosopher's Path. Sharing this route for anyone planning a thoughtful Japan trip.",type:"Trip experience",place:"Kyoto, Japan",likes:28,comments:6,time:"2h ago",color:"coral"},
 {id:2,user:"Daniel Okafor",initials:"DO",title:"Best local food in Rome?",text:"I have two evenings free near Trastevere. What is the one place or dish I should not miss?",type:"Question",place:"Rome, Italy",likes:14,comments:11,time:"5h ago",color:"blue"},
 {id:3,user:"Sofia Alvarez",initials:"SA",title:"Barcelona on a small budget",text:"A compact three-day route with markets, neighbourhood walks, and a sunset spot that costs absolutely nothing.",type:"Travel tip",place:"Barcelona, Spain",likes:41,comments:9,time:"Yesterday",color:"gold"},
 {id:4,user:"Arjun Mehta",initials:"AM",title:"Desert stillness in Dubai",text:"The early morning safari was worth every minute of the wake-up call. The light over the dunes is unforgettable.",type:"Trip experience",place:"Dubai, UAE",likes:19,comments:3,time:"Yesterday",color:"green"}
];

export default function Community(){
 const[posts,setPosts]=useState(initialPosts);const[q,setQ]=useState("");const[type,setType]=useState("All posts");const[sort,setSort]=useState("Recent");const[liked,setLiked]=useState([]);
 const visible=useMemo(()=>posts.filter(post=>(type==="All posts"||post.type===type)&&`${post.title} ${post.text} ${post.place}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="Popular"?b.likes-a.likes:a.id-b.id),[posts,q,type,sort]);
 const toggleLike=id=>{setLiked(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);setPosts(current=>current.map(post=>post.id===id?{...post,likes:post.likes+(liked.includes(id)?-1:1)}:post))};
 return <section className="page community-page"><PageHeader title="Community" subtitle="Share the places, stories, and small discoveries that make travel better." action={<button className="btn btn-primary"><Plus size={17}/> Share an experience</button>}/><div className="community-intro"><div><span className="eyebrow">Travel together</span><h2>Find your people, wherever you are going.</h2><p>Ask a question, share a route, or leave a note for the next traveler.</p></div><div className="community-stat"><strong>{posts.length}</strong><span>fresh stories<br/>from travelers</span></div></div><div className="community-toolbar"><label><Search size={16}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search a trip, activity, or place"/></label><select value={type} onChange={event=>setType(event.target.value)} aria-label="Filter community posts"><option>All posts</option><option>Trip experience</option><option>Travel tip</option><option>Question</option></select><button className="btn btn-outline"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort community posts"><option>Recent</option><option>Popular</option></select><SlidersHorizontal size={17} className="community-sliders"/></div><div className="community-heading"><div><span className="eyebrow">From the community</span><h2>Latest conversations</h2></div><span>{visible.length} posts</span></div><div className="community-feed">{visible.map(post=><article className="community-post" key={post.id}><div className={`post-avatar ${post.color}`}>{post.initials}</div><div className="post-main"><div className="post-meta"><div><b>{post.user}</b><span>{post.time}</span></div><span className="post-type">{post.type}</span></div><h3>{post.title}</h3><p>{post.text}</p><div className="post-place">📍 {post.place}</div><div className="post-actions"><button className={liked.includes(post.id)?"liked":""} onClick={()=>toggleLike(post.id)}><Heart size={15} fill={liked.includes(post.id)?"currentColor":"none"}/> {post.likes}</button><button><MessageCircle size={15}/> {post.comments}</button><button><Share2 size={15}/> Share</button></div></div></article>)}{!visible.length&&<div className="community-empty">No conversations match your search.</div>}</div></section>
}
