import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {ArrowRight,Filter,Plus,Search,SlidersHorizontal} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import TripCard from "../components/trips/TripCard";
import {cities} from "../data/mockData";
import {tripAPI} from "../services/api";
import {useAuth} from "../context/AuthContext";

const regions=["All regions","Europe","Asia","Middle East"];
const formatTrip=trip=>({...trip,dates:`${trip.startDate} – ${trip.endDate}`,destinations:trip.stops?.length||0,cities:trip.stops?.map(stop=>stop.city)||[],budget:Object.values(trip.budget||{}).reduce((total,value)=>total+Number(value||0),0),status:"Planning"});

export default function Dashboard(){
 const{user}=useAuth();const[trips,setTrips]=useState([]);const[query,setQuery]=useState("");const[region,setRegion]=useState("All regions");const[sort,setSort]=useState("Popular");
 useEffect(()=>{tripAPI.list().then(setTrips).catch(()=>{})},[]);
 const visibleCities=cities.filter(city=>(region==="All regions"||city.region===region)&&`${city.name} ${city.country}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Popular"?b.popularity-a.popularity:a.name.localeCompare(b.name));
 return <section className="page landing-page"><PageHeader title={`Welcome, ${user?.name||"Traveler"} 👋`} subtitle="Your personal space for planning the next unforgettable journey." action={<Link className="btn btn-primary" to="/create-trip"><Plus size={18}/> Plan New Trip</Link>}/><div className="landing-banner"><div><span className="banner-kicker">Travel farther, plan smarter</span><h2>There is a whole world<br/>waiting for your next story.</h2><p>Find inspiration, save your ideas, and turn them into a trip that feels like yours.</p><Link className="banner-link" to="/cities">Explore destinations <ArrowRight size={16}/></Link></div><div className="banner-art" aria-hidden="true"><span>✦</span><b>GO<br/>WHERE<br/>YOU<br/>FEEL<br/>ALIVE</b></div></div><div className="explore-controls"><label className="dashboard-search"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search cities, countries, or regions"/></label><div className="control-actions"><select value={region} onChange={event=>setRegion(event.target.value)} aria-label="Group by region">{regions.map(option=><option key={option}>{option}</option>)}</select><button className="btn btn-outline control-button"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort destinations"><option>Popular</option><option>Alphabetical</option></select><SlidersHorizontal className="control-sliders" size={17}/></div></div><section className="flat-section"><div className="section-heading"><div><span className="eyebrow">Handpicked inspiration</span><h2>Top regional selections</h2></div><Link className="text-link" to="/cities">See all <ArrowRight size={15}/></Link></div><div className="regional-grid">{visibleCities.slice(0,5).map(city=><Link to="/cities" className="regional-card" key={city.name}><span className="regional-art">{city.emoji}</span><span><b>{city.name}</b><small>{city.country} · {city.cost} cost</small></span><ArrowRight size={15}/></Link>)}</div>{!visibleCities.length&&<div className="dashboard-empty">No destinations match your search.</div>}</section><section className="flat-section previous-section"><div className="section-heading"><div><span className="eyebrow">Pick up where you left off</span><h2>Previous trips</h2></div><Link className="text-link" to="/trips">View all <ArrowRight size={15}/></Link></div><div className="trip-grid landing-trips">{trips.slice(0,3).map(trip=><TripCard key={trip.id} trip={formatTrip(trip)}/>)}</div>{!trips.length&&<div className="dashboard-empty">Your saved trips will appear here after you plan one.</div>}</section></section>
}