import {useEffect,useMemo,useState} from "react";
import {CalendarDays,Eye,Filter,MoreHorizontal,Plus,Search,Trash2} from "lucide-react";
import {Link} from "react-router-dom";
import PageHeader from "../components/common/PageHeader";
import {tripAPI} from "../services/api";

const getState=trip=>{const start=new Date(`${trip.startDate}T00:00:00`);const end=new Date(`${trip.endDate}T23:59:59`);const now=new Date();return end<now?"Completed":start<=now?"Ongoing":"Upcoming"};
const normalize=trip=>({...trip,state:getState(trip),dates:`${trip.startDate} – ${trip.endDate}`,destinations:trip.stops?.length||0,budget:Object.values(trip.budget||{}).reduce((total,value)=>total+Number(value||0),0),cities:trip.stops?.map(stop=>stop.city).filter(Boolean)||[]});

function ListingCard({trip,onDelete}){return <article className="listing-card"><div className="listing-cover"><span>{trip.cities[0]==="Paris"?"🗼":trip.cities[0]==="Tokyo"?"🌸":"🌆"}</span><button className="listing-more" title="More trip actions"><MoreHorizontal size={18}/></button></div><div className="listing-body"><div className="listing-heading"><div><span className="listing-status">{trip.state}</span><h3>{trip.name}</h3></div><strong>${trip.budget.toLocaleString()}</strong></div><p>{trip.description||"A carefully planned journey waiting for its next detail."}</p><div className="listing-meta"><span><CalendarDays size={14}/>{trip.dates}</span><span>{trip.destinations} destinations</span></div><div className="listing-actions"><Link className="btn btn-outline small" to={`/trips/${trip.id}/itinerary`}><Eye size={15}/> View trip</Link><Link className="btn btn-quiet small" to={`/trips/${trip.id}/builder`}>Edit plan</Link><button className="delete-trip" title="Delete trip" onClick={()=>onDelete(trip.id)}><Trash2 size={15}/></button></div></div></article>}

export default function MyTrips(){
 const[trips,setTrips]=useState([]);const[query,setQuery]=useState("");const[group,setGroup]=useState("All trips");const[sort,setSort]=useState("Newest");
 useEffect(()=>{tripAPI.list().then(data=>setTrips(data.map(normalize))).catch(()=>setTrips([]))},[]);
 const filtered=useMemo(()=>trips.filter(trip=>(group==="All trips"||trip.state===group)&&`${trip.name} ${trip.description||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Name"?a.name.localeCompare(b.name):new Date(b.startDate)-new Date(a.startDate)),[trips,query,group,sort]);
 const remove=async id=>{try{await tripAPI.remove(id);setTrips(current=>current.filter(trip=>trip.id!==id))}catch(error){console.error(error)}};
 const renderGroup=(title,state)=>{const items=filtered.filter(trip=>trip.state===state);return <section className="listing-group" key={state}><div className="listing-group-title"><h2>{title}</h2><span>{items.length}</span></div>{items.length?<div className="listing-stack">{items.map(trip=><ListingCard key={trip.id} trip={trip} onDelete={remove}/>)}</div>:<div className="listing-empty">No {state.toLowerCase()} trips yet.</div>}</section>};
 return <section className="page trips-list-page"><PageHeader title="My trips" subtitle="Keep every journey in view, from the first idea to the final memory." action={<Link className="btn btn-primary" to="/create-trip"><Plus size={18}/> Plan a trip</Link>}/><div className="listing-toolbar"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search your trips"/></label><select value={group} onChange={event=>setGroup(event.target.value)} aria-label="Filter by trip stage"><option>All trips</option><option>Ongoing</option><option>Upcoming</option><option>Completed</option></select><button className="btn btn-outline"><Filter size={15}/> Filter</button><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort trips"><option>Newest</option><option>Name</option></select></div><div className="listing-summary"><span>{filtered.length} trips in your collection</span><span>Updated just now</span></div>{group==="All trips"?["Ongoing","Upcoming","Completed"].map(state=>renderGroup(state,state)):renderGroup(group,group)}</section>
}