import {useEffect,useState} from "react";
import {Bell,Camera,Check,ChevronRight,Globe2,Lock,Mail,MapPin,UserRound} from "lucide-react";
import {Link} from "react-router-dom";
import PageHeader from "../components/common/PageHeader";
import {tripAPI} from "../services/api";
import {useAuth} from "../context/AuthContext";

const tripDateState=trip=>new Date(`${trip.endDate}T23:59:59`)<new Date()?"Previous":"Preplanned";
function ProfileTrip({trip}){return <article className="profile-trip"><div className="profile-trip-art">{trip.name?.toLowerCase().includes("japan")?"🌸":"🌆"}</div><div className="profile-trip-content"><span>{tripDateState(trip)}</span><h3>{trip.name}</h3><p>{trip.startDate} – {trip.endDate}</p><Link className="profile-view" to={`/trips/${trip.id}/itinerary`}>View <ChevronRight size={14}/></Link></div></article>}

export default function Settings(){
 const{user}=useAuth();const[saved,setSaved]=useState(false);const[trips,setTrips]=useState([]);const[name,setName]=useState(user?.name||"");const[email,setEmail]=useState(user?.email||"");const[activeTab,setActiveTab]=useState("Profile");
 useEffect(()=>{tripAPI.list().then(setTrips).catch(()=>{})},[]);useEffect(()=>{setName(user?.name||"");setEmail(user?.email||"")},[user]);
 const initials=(name||"Traveler").split(" ").map(part=>part[0]).slice(0,2).join("").toUpperCase();const preplanned=trips.filter(trip=>tripDateState(trip)==="Preplanned");const previous=trips.filter(trip=>tripDateState(trip)==="Previous");
 const tabs=[{label:"Profile",icon:UserRound},{label:"Preferences",icon:Globe2},{label:"Notifications",icon:Bell},{label:"Privacy",icon:Lock}];
 return <section className="page profile-page"><PageHeader title="My profile" subtitle="Your details, travel preferences, and saved journeys in one place."/><div className="profile-hero"><div className="profile-avatar-wrap"><div className="profile-avatar">{initials}</div><button className="avatar-camera" title="Change profile photo"><Camera size={15}/></button></div><div className="profile-identity"><span className="eyebrow">Ekado traveler</span><h2>{name||"Your profile"}</h2><p><Mail size={14}/>{email||"Add your email address"}</p></div><button className="btn btn-outline" onClick={()=>setActiveTab("Profile")}><UserRound size={15}/> Edit details</button></div><div className="settings-tabs">{tabs.map(({label,icon:Icon})=><button key={label} className={activeTab===label?"active":""} onClick={()=>setActiveTab(label)}><Icon size={15}/> {label}</button>)}</div>{activeTab==="Profile"&&<div className="profile-grid"><form className="section-card profile-form" onSubmit={event=>{event.preventDefault();setSaved(true)}}><div className="profile-section-title"><h2>User details</h2><span>Editable</span></div><label>Full name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Preferred language<select defaultValue="English"><option>English</option><option>Hindi</option><option>Gujarati</option></select></label>{saved&&<p className="success-text"><Check size={15}/> Profile saved</p>}<button className="btn btn-primary">Save changes</button></form><aside className="profile-note"><MapPin size={20}/><span className="eyebrow">Travel identity</span><h3>Make every trip feel like yours.</h3><p>Your profile helps keep planning personal, from the places you save to the pace you prefer.</p></aside></div>}{activeTab!=="Profile"&&<SettingsPanel tab={activeTab}/>}<ProfileCollection title="Preplanned Trips" trips={preplanned} empty="Trips you are planning will show up here."/><ProfileCollection title="Previous Trips" trips={previous} empty="Completed journeys will become part of your travel story here."/></section>
}
function ProfileCollection({title,trips,empty}){return <section className="profile-collection"><div className="profile-section-title"><h2>{title}</h2><span>{trips.length} saved</span></div>{trips.length?<div className="profile-trip-grid">{trips.map(trip=><ProfileTrip key={trip.id} trip={trip}/>)}</div>:<div className="profile-empty">{empty}</div>}</section>}
function SettingsPanel({tab}){const content={Preferences:{title:"Planning preferences",text:"Choose the pace and details that shape your future itineraries.",items:["Prefer local experiences","Show budget-friendly ideas","Use metric measurements"]},Notifications:{title:"Trip notifications",text:"Stay informed about the moments that matter to your plans.",items:["Trip reminders","Budget alerts","Community recommendations"]},Privacy:{title:"Privacy and security",text:"Keep your account and travel plans under your control.",items:["Private profile","Require confirmation before sharing","Activity visibility"]}}[tab];return <div className="section-card settings-panel"><div className="profile-section-title"><div><span className="eyebrow">Settings</span><h2>{content.title}</h2></div><span>Auto-loaded</span></div><p>{content.text}</p>{content.items.map(item=><label className="setting-toggle" key={item}><span><b>{item}</b><small>Enabled for your account</small></span><input type="checkbox" defaultChecked/></label>)}</div>}